### PR TITLE
Fix Ed consumption / adventures problem

### PR DESCRIPTION
**Pull request by mikebryant**

### CODE REVIEW

**Comment by mikebryant** [comment]
Gonna do a bit more work on this, think I can make the ed quest handling better

**Comment by mikebryant** [comment]
I think this works. Need to test it again from the beginning next ascension, I guess

**Comment by mapledyne** [comment]
I have a test account that is close to this point - will try it against that in a bit here. 

One thing I'd like the script to also do (but can be a future effort) is to run the consume() process to eat/drink something to gain adventures at this point - if we're low on adv but have room in our stomach/liver/spleen, we could just get more adventures if we're otherwise ready to do Ed soon.

**Comment by mikebryant** [comment]
That's what I was trying to do here: https://github.com/mapledyne/yaaz/pull/69/files#diff-ae81c993c4c62cb1bf598e6e6297af73R108

`prep` calls consume, so we should have above the adventure floor.
And I added warnings to the setup if anyone every sets it below 8

**Comment by mapledyne** [comment]
Oh right - I didn't think through the whole process and how that'd be automatically triggered given what you did. Sweet.

**Comment by mikebryant** [comment]
I've been through this another 2 times, I'm happy

**Pull request merged**
